# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "1.47.0"
default_platform(:ios)

platform :ios do

  
  desc "Run all the tests"
  lane :test do
    scan(device: "Iphone 6s (9.2)")
  end
end
